version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-idtypedemo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: idtypedb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - idtypedemo-network

  postgres:
    image: postgres:15
    container_name: postgres-idtypedemo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idtypedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - idtypedemo-network

volumes:
  mysql-data:
  postgres-data:

networks:
  idtypedemo-network:
    driver: bridge 